### ISSUE TITLE
Bitbox latest firmware doesn't work with tokens on MyEtherWallet

### ISSUE THREAD

**Issue by baero** [digitalbitbox/bitbox-base#100]
Again, it's not possible to send tokens with MyEtherWallet

https://www.reddit.com/r/MyEtherWallet/comments/c3m7ye/digital_bitbox_doesnt_work_with_myetherwallet/ery3j8r?utm_source=share&utm_medium=web2x

**Comment by Stadicus** [comment]
Thanks for reaching out. This issue should be filed in the right repository here:
https://github.com/digitalbitbox/bitbox-wallet-app

cc: @benma
