### ISSUE TITLE
Question: LIB_TAG sunxi-4.20

### ISSUE THREAD

**Issue by NicolasDorier** [digitalbitbox/bitbox-base#106]
Is there a reason why you use the tag sunxi-4.20 beside it being the latest release?
On the main armbian repo, I want to try master, but I am not sure if I would not break something else down the road.

**Comment by Stadicus** [comment]
There's nothing stopping you to just remove the LIB_TAG, this should not break something systemically. We pinned the tag to avoid having a moving target and pulling in new code from the master branch all the time. We did not test the master branch build for about a month now.

Any special reason to build directly from master, like a specific improvement or feature?

**Comment by NicolasDorier** [comment]
Yes, this commit: https://github.com/armbian/build/commit/5b9d2110c668c010708cd7f351ef911c92fd7eeb#diff-3254677a7917c6c01f55212f86c57fbf

This will dramatically speed up updating the image.

**Comment by NicolasDorier** [comment]
Oh actually `sunxi-5.0` released with this commit, can we update to it?

**Comment by Stadicus** [comment]
Let's test it locally to see if it introduces any os issues, and then we can bump the fixed version to `sunxi-5.0`. I can do that next week, let me know if you have earlier results.

**Comment by NicolasDorier** [comment]
ok, I am trying on my own fork. I am battling in the customize image to download the docker images :(
Running a docker inside a docker which run on qemu is not as simple as I thought :(

**Comment by Stadicus** [comment]
Closing this issue as we're currently building from master branch without any issues. Need to lock in the release / commit when going from DEV to TEST/PROD mode, though.
