### ISSUE TITLE
Implement Base Supervisor

### ISSUE THREAD

**Issue by Stadicus** [digitalbitbox/bitbox-base#115]
This issue tracks the progess in implementing the **BitBox Base Supervisor** (bbbsupervisor), written in Go. The code and docuumentation is located in [bitbox-base/tools/bbbsupervisor](https://github.com/digitalbitbox/bitbox-base/tree/master/tools/bbbsupervisor).

**Features**
System control
- [x] fan control: 
  * implemented as [bbbfancontrol](https://github.com/digitalbitbox/bitbox-base/tree/master/tools/bbbfancontrol)
- [ ] monitor disk space
  - action: warn user through app
  - very tight logrotation and read-only rootfs already implemented

Bitcoin Core
- [x] detect initial block download: query Prometheus for `bitcoind_ibd=1`
  - actions: 
    - touch or delete `/data/systemd-triggers/bitcoind-fully-synced`
    - set dbcache to 300MB or 2000GB with e.g. `bbb-config set bitcoin_dbcache 300`
    - when IBD finished, start `lightningd` and `electrs`
- [ ] detect no space left: monitor journal for `No space left on device`
  - action: warn user through app

Electrs
- [x] detect auth failure to bitcoind: 
  - monitor journal for `WARN - reconnecting to bitcoind: no reply from daemon`
  - actions: 
    - recreate bitcoind cookie env file `/mnt/ssd/bitcoin/.bitcoin/.cookie.env`
    - restart `electrs.service`

**Comment by 0xB10C** [comment]
- [ ] As per discussion with @Stadicus: change electrs start-script to rewrite the bitcoind .cookie file everytime (before) electrs is started. 

The only action for Electrs _"detect auth failure to bitcoind"_ is now to restart `electrs.service`.

**Comment by 0xB10C** [comment]
https://github.com/digitalbitbox/bitbox-base/pull/120 implements the features for electrs and Bitcoin Core. However the trigger on low disk space is still open.

**Comment by Stadicus** [comment]
Base implementation is complete, next tasks will be tracked by follow-up issues
