### ISSUE TITLE
Mender's image won't boot from SD card

### ISSUE THREAD

**Issue by x1ddos** [digitalbitbox/bitbox-base#290]
Here's what I see from the serial output while trying to boot `bin/img-mender/0.1.0/BitBoxBase-v0.1.0-RockPro64.img` created from `bin/img-armbian/BitBoxBase_Armbian_RockPro64.img` with `make -C armbian mender-artefacts`, all built from commit d2d75f0 aka latest tag 0.1.0. 

```
vcc-phy-regulator@vcc_phy: ; enabling (ret: -38)
vdd-log@vdd_log: ; enabling (ret: -38)
MMC:   sdhci@fe330000: 0, dwmmc@fe320000: 1
Card did not respond to voltage select!
mmc_init: -95, time 19
*** Warning - No block device, using default environment

In:    serial@ff1a0000
Out:   serial@ff1a0000
Err:   serial@ff1a0000
Model: Pine64 RockPro64
normal boot
Net:   eth0: ethernet@fe300000
Hit any key to stop autoboot:  0
Card did not respond to voltage select!
mmc_init: -95, time 21
switch to partitions #0, OK
mmc1 is current device
Scanning mmc 1:1...
Found U-Boot script /boot.scr
reading /boot.scr
3136 bytes read in 3 ms (1020.5 KiB/s)
## Executing script at 00500000
Saving Environment to MMC...
Card did not respond to voltage select!
mmc_init: -95, time 20
!No block device
Boot script loaded from mmc 0:1
Card did not respond to voltage select!
mmc_init: -95, time 20
** Bad device mmc 0 **
Card did not respond to voltage select!
mmc_init: -95, time 21
"Synchronous Abort" handler, esr 0x96000010
ELR:     f7f6dd5c
LR:      f7f1b160
x0 : 0000000000000000 x1 : 0000000000000002
x2 : 0000000000000010 x3 : 0000000000000000
x4 : 00000000f7f81df0 x5 : 0000000000000002
x6 : 0000000000000008 x7 : 0000000000000044
x8 : 0000000000000001 x9 : 0000000000000008
x10: 00000000f5f0043f x11: 0000000000000006
x12: 000000000001869f x13: 00000000ffffffff
x14: 00000000f5f0297c x15: 00000000ffffffff
x16: 000000001e534356 x17: 00000000104080aa
x18: 00000000f5f0ee08 x19: 0000000000000000
x20: 00000000f5f34170 x21: 00000000f5f34100
x22: 00000000f7fb1000 x23: 00000000f5f34120
x24: 0000000000000000 x25: 00000000f5f35290
x26: 0000000000000000 x27: 0000000000000000
x28: 0000000000000000 x29: 00000000f5f009a0

Resetting CPU ...
```
and then it repeats all over again in an endless loop.

However, booting the same image pre Mender's convertion (`bin/img-armbian/BitBoxBase_Armbian_RockPro64.img`) works fine:

```
In:    serial@ff1a0000
Out:   serial@ff1a0000
Err:   serial@ff1a0000
Model: Pine64 RockPro64
Net:   eth0: ethernet@fe300000
Hit any key to stop autoboot:  0
Card did not respond to voltage select!
mmc_init: -95, time 20
switch to partitions #0, OK
mmc1 is current device
Scanning mmc 1:1...
Found U-Boot script /boot/boot.scr
2949 bytes read in 30 ms (95.7 KiB/s)
## Executing script at 00500000
Boot script loaded from mmc 1
167 bytes read in 23 ms (6.8 KiB/s)
7803492 bytes read in 873 ms (8.5 MiB/s)
20987912 bytes read in 2276 ms (8.8 MiB/s)
96273 bytes read in 203 ms (462.9 KiB/s)
** File not found /boot/dtb/rockchip/overlay/rockchip-fixup.scr **
## Loading init Ramdisk from Legacy Image at 04000000 ...
   Image Name:   uInitrd
   Image Type:   AArch64 Linux RAMDisk Image (gzip compressed)
   Data Size:    7803428 Bytes = 7.4 MiB
   Load Address: 00000000
   Entry Point:  00000000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 01f00000
   Booting using the fdt blob at 0x1f00000
   Loading Ramdisk to f5790000, end f5f01224 ... OK
   reserving fdt memory region: addr=1f00000 size=7d000
   Loading Device Tree to 00000000f5710000, end 00000000f578ffff ... OK

Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Initializing cgroup subsys cpuacct
[    0.000000] Linux version 4.4.198-rockchip64 (root@builder) (gcc version 8.3.0 (GNU Toolchain for the A-profile Architecture 8.3-2019.03 (arm-rel-8.36)) ) #3 SMP Tue Nov 19 00:05:14 CET 2019
[    0.000000] Boot CPU: AArch64 Processor [410fd034]
[    0.000000] earlycon: Early serial console at MMIO32 0xff1a0000 (options '')
[    0.000000] bootconsole [uart0] enabled
```

My SD card is just a regular Kingston 16Gb class 10.

The hardware is practically identical to https://base.shiftcrypto.ch/hardware/components.html except I'm using a consumer version of PCIe M.2 SSD adapter, and my USB UART doesn't have the issue described in https://base.shiftcrypto.ch/hardware/hsm/hsm-uart.html. But I don't think it all matters given the base armbian image boots.

At the time of the images build, https://github.com/armbian/build was at commit 35e69432988106d7bc0e6895c36010f5426ee5ef and https://github.com/mendersoftware/mender-convert at 56f4123864100cc81d87d3b6f66274d23d2177ba, which BTW another point - maybe these need to be pinned to a specific commit instead of always "git clone ..." from whatever their master/HEAD is, or use submodules or something else.

**Comment by x1ddos** [comment]
Forgot to add. I inspected the Mender's image and it appears to be of a reasonable side with all partitions. I can loop-mount it locally and from the SD card once `dd`'ed.

```
$ ls -lha bin/img-mender/0.1.0/
total 1.9G
drwxr-xr-x 2 4.0K Nov 30 14:25 .
drwxr-xr-x 3 4.0K Nov 30 14:24 ..
-rw-r--r-- 1 215M Nov 30 14:20 BitBoxBase-v0.1.0-RockPro64.base-unsigned
-rw-r--r-- 1 7.9G Nov 30 14:41 BitBoxBase-v0.1.0-RockPro64.img
-rw-r--r-- 1 377M Nov 30 14:25 BitBoxBase-v0.1.0-RockPro64.tar.gz

$ fdisk -l bin/img-mender/0.1.0/BitBoxBase-v0.1.0-RockPro64.img
Disk bin/img-mender/0.1.0/BitBoxBase-v0.1.0-RockPro64.img: 7.83 GiB, 8384413696 bytes, 16375808 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xeb16267b

Device                                                Boot    Start      End Sectors  Size Id Type
bin/img-mender/0.1.0/BitBoxBase-v0.1.0-RockPro64.img1 *       24576    40959   16384    8M  c W95 FAT32 (LBA)
bin/img-mender/0.1.0/BitBoxBase-v0.1.0-RockPro64.img2         40960  8077311 8036352  3.9G 83 Linux
bin/img-mender/0.1.0/BitBoxBase-v0.1.0-RockPro64.img3       8077312 16113663 8036352  3.9G 83 Linux
bin/img-mender/0.1.0/BitBoxBase-v0.1.0-RockPro64.img4      16113664 16375807  262144  128M 83 Linux
```

**Comment by x1ddos** [comment]
Another note: I did of course try different SD cards, just to rule it out.

**Comment by Stadicus** [comment]
Never experienced that issue. Could you add the cli output of the `mender-convert` script?

Also, it would be interesting to see if the issue is SD card specific and if this image works of an eMMC.

**Comment by x1ddos** [comment]
Interesting. I've just tried booting that same Mender's converted image from eMMC and it works.

Going to clean and do it again. Maybe you could also try and reproduce? If you do, make sure your armbian-build and mender-convert repos are checked out at or past the commit hashes above.

**Comment by x1ddos** [comment]
No, exact same result. Won't boot from SD card. eMMC works.
Attaching output from "make build-all" in case there's anything interesting.
[buildlog-base-2019-12-03.txt](https://github.com/digitalbitbox/bitbox-base/files/3919057/buildlog-base-2019-12-03.txt)

**Comment by Stadicus** [comment]
Thanks for the log, this looks as expected. We collaborated with Mender to bring their solution to the RockPro64 board, specifically to boot from eMMC storage. 

Booting from SD card was not the goal, as these wear out pretty quickly. It might still be feasible to run Armbian from SD card, mounting it as read-only, but we're exclusively using eMMC storage at the moment.

Additional work would be needed to make this SD card compatible, which is currently not in scope.

**Comment by x1ddos** [comment]
I see. Didn't realize this is expected.
Thanks.

**Comment by Stadicus** [comment]
Thanks for testing it anyway. Realized we nowhere stated the restriciton to eMMC and added this here: https://github.com/digitalbitbox/bitbox-base/pull/297
