### ISSUE TITLE
Don't bundle "random" keys in armbian/base/config/ssh/authorized_keys

### ISSUE THREAD

**Issue by x1ddos** [digitalbitbox/bitbox-base#292]
It feels kind of weird that building the image by default includes "random" keys in https://github.com/digitalbitbox/bitbox-base/blob/d2d75f06f7fcde655209bbb11a01faafa3fb26c1/armbian/base/config/ssh/authorized_keys#L1-L4

Maybe a better option would be to add `armbian/base/config/ssh/authorized_keys` to .gitignore and document better how to add a key in the config? Say, somewhere around https://github.com/digitalbitbox/bitbox-base/blob/d2d75f06f7fcde655209bbb11a01faafa3fb26c1/armbian/base/build.conf#L23-L24

**Comment by Stadicus** [comment]
This is for internal development purposes only and `off` by default.

But I agree, now that we reached a stage where we reliably can connect with the BitBoxApp and set the login password, we can remove that.
