### ISSUE TITLE
master branch of mender-convert no longer works

### ISSUE THREAD

**Issue by lausser** [digitalbitbox/bitbox-base#327]
In armbian/mender-convert.sh you call 
git clone -b master …. mender-convert
During the conversion of the image, the build fails with

 [mender-convert-extract] Sorry but the provided option is not supported: from-raw-disk-Image

I see that the master branch of mender-convert has changed two days ago and the command line Parameters used by bitbox-base no longer work.
If you pull 1.2.2 instead of master, then it works again.

**Comment by Stadicus** [comment]
Thanks for pointing this out, should be fixed with the referenced pull-request. Will investigate the changes  they made and the reasoning behind them.
