### ISSUE TITLE
Switch to Docker for Armbian build

### ISSUE THREAD

**Issue by hkjn** [digitalbitbox/bitbox-base#39]
In our current build process, we use VirtualBox VMs managed by Vagrant to build the Armbian-based OS images for the Base:

* https://base.shiftcrypto.ch/os/armbian-build.html

This has some downsides:

* all developers or automated systems need Vagrant and VirtualBox installed, with specific versions; in comparison, Docker is becoming a standard dependency to manage dependencies of various tech stacks for many developers
* we already use Docker in the Base project for [building Go programs](https://github.com/digitalbitbox/bitbox-base/blob/master/Dockerfile), so using it for Armbian builds would reduce the set of dependencies
* having several virtualization technologies in the same repo has already led to [unfortunate interactions / extra complexity](https://github.com/digitalbitbox/bitbox-base/pull/37#issuecomment-498755381), so just relying on Docker would be preferable

This work was earlier discussed in a [PR comment thread](https://github.com/digitalbitbox/bitbox-base/pull/26#issuecomment-496948578).

The official Armbian docs for building with Docker are available at:

* https://docs.armbian.com/Developer-Guide_Building-with-Docker/

This issue can be closed once support for building Armbian OS images with Docker has been merged to `master`, or if we decide not to pursue this.

**Comment by hkjn** [comment]
I tried making the changes to `armbian/build.sh` to switch to Docker-based builds for Armbian OS images in https://github.com/digitalbitbox/bitbox-base/commit/6fbda4cd15297949c134c9060f5e05061a2eae59.

The [branch](https://github.com/digitalbitbox/bitbox-base/compare/master...hkjn:20190605-dockerize-armbian?expand=1) seems to build fine locally, and produces an `.img` file that boots on a RockPro64 board and which seems functional on cursory examination, however on Travis the build errors:

* https://travis-ci.org/hkjn/bitbox-base/builds/542162183

The symptom seen on Travis builds is: 
```
# Successfully built b1561d8cbb3b
# Successfully tagged armbian:latest
# [ o.k. ] Running the container 
# docker: Error response from daemon: create ./: "./" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
# See 'docker run --help'.
# [ error ] Docker command failed, check syntax or version support. Error code:   [ 125 ]
```

The part of the build that fails seems to be L79 in [`config-docker.conf`](https://github.com/armbian/build/blob/sunxi-4.20/config-docker.conf#L79), where the Armbian script tries to run:

```
docker run "${DOCKER_FLAGS[@]}" -it armbian docker-guest "$@"
```

The error from the Travis logs seems to indicate a syntax error in the arguments to `docker run`. It's a bit tricky to get more information as this script is checked out by [our build.sh](https://github.com/digitalbitbox/bitbox-base/commit/6fbda4cd15297949c134c9060f5e05061a2eae59#diff-8606993d39dd77fe9475ba95ca542787L51) script during the Travis build..

I'll try finding out what the full `docker run` command is during local builds to start with, and then look for options for figuring out what's different / what's going wrong when Travis runs the build.

**Comment by hkjn** [comment]
In [a branch](https://github.com/digitalbitbox/bitbox-base/compare/master...hkjn:20190605-debug-travis?expand=1), I've added the entire armbian repo in a commit, to be able to debug the issue with building using Docker that was seen on Travis builds.

I found that [config-docker.conf](https://github.com/armbian/build/blob/sunxi-4.20/config-docker.conf#L79) on L79 tries to run a command like:

```
$ docker run --cap-add=SYS_ADMIN --cap-add=MKNOD --cap-add=SYS_PTRACE --security-opt=apparmor:unconfined --device=/dev/loop0 --device=/dev/loop1 --device=/dev/loop2 --device=/dev/loop3 --device=/dev/loop4 --device=/dev/loop5 --device=/dev/loop6 --device=/dev/loop7 --device=/dev/loop-control --device-cgroup-rule='b 7:* rmw' --device-cgroup-rule='b 259:* rmw' -v /dev:/tmp/dev:ro -v=.:/root/armbian/ -v=armbian-cache:/root/armbian/cache -v=armbian-ccache:/root/.ccache -it armbian docker-guest BOARD=rockpro64 KERNEL_ONLY=no KERNEL_CONFIGURE=no RELEASE=stretch BRANCH=default BUILD_DESKTOP=no WIREGUARD=no LIB_TAG=sunxi-4.20
```

This fails with the error message seen earlier:
```
# docker: Error response from daemon: create ./: "./" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
```

The failure seems to be due to `SRC` having the value `.`, whereas the `-v` / `--volume` arguments to Docker need to hold the absolute path. If I patch `config-docker.conf` to set it to the value of `$(pwd)` instead as in https://github.com/digitalbitbox/bitbox-base/commit/40704ff, this issue no longer is seen.

I have as of yet not followed the logic of where the `SRC` variable gets its value, and why this issue is only seen when running on Travis, but this might represent a genuine issue / room for improvement for the armbian project.

**Comment by hkjn** [comment]
As another update, I noticed a further potential issue when running on Travis.

Without the https://github.com/hkjn/bitbox-base/commit/3ba9c6ff925c1ef7a7756c7b3cac59fa96e95a0c commit, the command inside `config-docker.conf` would run `docker run -it <...>`. As seen in e.g [this build](), that led to the command erroring with `the input device is not a TTY`. Removing the `-t` seems to allow the build to proceed.

The current issue is that the build [fails abruptly](https://travis-ci.org/hkjn/bitbox-base/builds/544741241), seemingly due to the Travis timeout:
```
[...]
  LD      net/vmw_vsock/built-in.o
  CC [M]  net/vmw_vsock/af_vsock.o
  CC [M]  drivers/net/ipvlan/ipvlan_main.o
The command "travis_wait 40 ./scripts/travis-ci.sh" exited with 137.
```

I've been [progressively bumping](
https://github.com/hkjn/bitbox-base/commit/edf40ca18e961733438d04deb4f477fcb48736bb) the timeout using the `travis_wait` [wrapper script](https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received) to find a value that allows Travis to finish the build process.

**Comment by hkjn** [comment]
Looks like we've now hit the 50 min maximum [timeout for an individual job](https://docs.travis-ci.com/user/customizing-the-build#build-timeouts):

* https://travis-ci.org/hkjn/bitbox-base/builds/544765465#L459

I'm guessing it will be hard to improve things from here. The options as I see them are:

- figure out why Armbian builds are slow on Travis, and make them faster
- break up the Armbian build into several individual jobs
- don't add Armbian builds to Travis CI

To be clear, I believe switching the Armbian OS builds from VirtualBox+Vagrant to Docker still has advantages, and since we don't have CI configured for building these artifacts right now, there's no regression by not getting it working on Travis. I'll look around a bit more, then clean up and prep a PR that switches to Dockerized Armbian builds.

**Comment by hkjn** [comment]
The work for this issue has been mostly addressed, and we have switched over to using the Dockerized Armbian builds by default when we're running `make` at this point.

We'll leave this issue open for now, until we've sent PRs for the upstream fixes to the Armbian project that were mentioned earlier in https://github.com/digitalbitbox/bitbox-base/issues/39#issuecomment-501306986.

Even after upstreaming those fixes, we likely won't pursue switching Travis over due to the [timeout issue](https://github.com/digitalbitbox/bitbox-base/issues/39#issuecomment-501306986), but it does seem good to clear the path for doing so by addressing the other two problems.

**Comment by Stadicus** [comment]
Armbian build has been moved to Docker completely. Integration of nightly builds in CI system is a separate topic.
