### ISSUE TITLE
Add integration tests to CI

### ISSUE THREAD

**Issue by hkjn** [digitalbitbox/bitbox-base#65]
As mentioned in https://github.com/digitalbitbox/bitbox-base/pull/62:

> It would be nice, if the dockerfile would include regtest setups of c-lightning and bitcoind to check if the middleware is still capable of communicating / routing traffic with them.

We have a `travis-ci.sh` script which Travis [runs on every commit](https://github.com/digitalbitbox/bitbox-base/blob/master/.travis.yml#L17). At time of writing, the `make docker-build-go` target is invoked by Travis, but we can easily add more `make` targets to add regression tests, as described above.

We might also want to check that all links in `docs/` resolve, as suggested [here](https://github.com/digitalbitbox/bitbox-base/pull/69).

This issue can be closed once integration tests have been added to CI, or if we decide not to pursue this work.

**Comment by hkjn** [comment]
I'll unassign myself from this issue, since I don't think I'll have time to work on this anytime soon. (It's a fairly complex task; we'd want to avoid a hacked up integration test that would take more time to maintain than the time saved due to improved quality assurance through automatic tests.)

**Comment by Stadicus** [comment]
@TheCharlatan: please define requirements of CI tests

**Comment by TheCharlatan** [comment]
Opened https://github.com/digitalbitbox/bitbox-base/pull/110 , which adds a bunch of unit test to the ci Makefile target.
