### ISSUE TITLE
De-dupe configs and systemd units between docs and source code

### ISSUE THREAD

**Issue by hkjn** [digitalbitbox/bitbox-base#71]
As discussed in https://github.com/digitalbitbox/bitbox-base/pull/53, we are currently describing the configuration of services like `bitcoin.conf` for `bitcoind` in quite a lot of detail in our [docs/](https://github.com/digitalbitbox/bitbox-base/tree/master/docs):

* https://base.shiftcrypto.ch/applications/bitcoin-core.html

There's many other such config files, systemd services which currently duplicates the configs and adds commentary within `docs/`.

We also define the actual configs like `bitcoin.conf`, at time of writing inside the `customize-armbian-rockpro64.sh` script:

* https://github.com/digitalbitbox/bitbox-base/blob/master/armbian/base/build/customize-armbian-rockpro64.sh#L313

We should consider work to:

- [ ] refactor out configs from `customize-armbian-rockpro64.sh`
- [ ] update the standalone config files to include as much of the comments and context as makes sense from the docs
- [ ] create some templated `.md` files with placeholder values for the actual config contents
- [ ] add a preprocessor script that reads the templated `.md` files as well as the config files and renders the concrete `.md` files
- [ ] add some warning to not edit the autogenerated `.md` files
- [ ] add CI support for regenerating the `.md` files, or at least giving an error if the generated files are not up-to-date

**Comment by thisconnect** [comment]
>  create some templated .md files with placeholder values for the actual config contents

similar how the `wlan0.conf` is done (with `{wpa-ssid}` and `{wpa-psk}`)?

**Comment by hkjn** [comment]
> > create some templated .md files with placeholder values for the actual config contents
> 
> similar how the `wlan0.conf` is done (with `{wpa-ssid}` and `{wpa-psk}`)?

Yeah, exactly. The concrete `.md` files can be rendered by some preprocessor script, inserting the actual configs where placeholders like `{bitcoin-conf}` are. We could run those preprocessors on CI to assert that the `.md` files are in sync with what would be generated from the templates.

**Comment by Stadicus** [comment]
This issue has become obsolete due to creating the config files from tempaltes with `bbbconfgen`, see https://github.com/digitalbitbox/bitbox-base/pull/160

* config files are now no longer inline
* the cannot be easily integrated into the documentation, however, as they are created on the fly

For the moment, the docs are maintained manually.
