### ISSUE TITLE
/bin/bash no such file or directory

### ISSUE THREAD

**Issue by NicolasDorier** [digitalbitbox/bitbox-base#83]
```bash
make
```

![image](https://user-images.githubusercontent.com/3020646/59745938-cba50600-92b0-11e9-93b5-f428c04f7770.png)

I tried to register qemu on the host, but it does not seems to have worked

```bash
docker run --rm --privileged multiarch/qemu-user-static:register
```

**Comment by NicolasDorier** [comment]
At one point I also got 

![image](https://user-images.githubusercontent.com/3020646/59746203-5b4ab480-92b1-11e9-8a00-c097dcdf7c61.png)

I am wondering if this is some qemu trickery going on.

**Comment by hkjn** [comment]
@NicolasDorier: Do you have some docs or other reference explaining what running `multiarch/qemu-user-static:register` does?

Or for that matter, could you provide some context as to what you are trying to do here? :)

**Comment by NicolasDorier** [comment]
@hkjn just trying to run `make`

`multiarch/qemu-user-static:register` install qemu on the docker host. It solved some issues I had in the past when trying to use ARM32 on docker x64.

**Comment by hkjn** [comment]
> @hkjn just trying to run make

Oh, okay. Is your host environment `x86_64` + Windows 10?

I'm not sure what's going wrong here; if `/bin/bash` wasn't present inside the container used for the Armbian build, I'd expect that things would fail a lot sooner..

I'm not sure how installing qemu would change anything, but I'm not at all familiar with Windows environments and how / if it enters the mix / is required there. I'd be happy to learn more / take a look but would need to get access to an environment where I could repro the issue to start with.

If you want to dig further yourself, https://base.shiftcrypto.ch/os/build-details.html has some info about the overall Armbian build process and how we make use of it. I'll also try to unpack some stuff below in case it's helpful:

1. our [build.sh](https://github.com/digitalbitbox/bitbox-base/blob/master/armbian/build.sh#L50) script calls armbian's [compile.sh](https://github.com/armbian/build/blob/master/compile.sh) with the `docker` argument
1. `compile.sh` eventually kicks off the `docker run` command which starts the container performing the build in [config-docker.conf](https://github.com/armbian/build/blob/master/config-docker.conf#L83)

Based on the screenshot you posted, it looks like the Armbian build process fails during the `chroot` to the OS image being built, which I believe is fairly late in the build process.

**Comment by NicolasDorier** [comment]
@hkjn environent is on an ubuntu.

**Comment by NicolasDorier** [comment]
mmmh ok. Yeah I read a lot about how armbian works. But this problem happened right after the switch to docker so I thought maybe something wrong here.

**Comment by hkjn** [comment]
> @hkjn environment is on an ubuntu.

Okay, that's even weirder then..

My base system is on Debian, which should be quite similar. What does `docker --version` / `docker info` produce?

**Comment by hkjn** [comment]
Oh, also, what version of Ubuntu? (Via e.g `cat /etc/os-release`.)

**Comment by NicolasDorier** [comment]
@hkjn  I am not at work anymore, will check tomorrow. But it must come from my environment or armbian rather than this repo. Will keep you updated when I managed to fix it.

**Comment by Stadicus** [comment]
I can confirm that building Armbian works on my machine using:
* Ubuntu 18.04 LTS
* Docker version 18.09.6, build 481bc77
* see [`docker info` on Pastebin](https://pastebin.com/kLDutFPH) for more info

**Comment by NicolasDorier** [comment]
This fixed it:

```bash
sudo apt-get install qemu binfmt-support qemu-user-static
```

That was the host that was not properly configured for running qemu. It may be wise to mention in the doc somewhere.

**Comment by hkjn** [comment]
> This fixed it: (on the host)
> 
> ```shell
> sudo apt-get install qemu binfmt-support qemu-user-static
> ```
> 
Glad you figured it out!

> That was the host that was not properly configured for running qemu. It may be wise to mention in the doc somewhere.

I'd love to include a note in the docs, but I don't really understand how qemu enters into it at all, as I was unware that we had any dependency on it (direct or indirect).. do you have any hint for why qemu is needed to do the build in your environment?

**Comment by NicolasDorier** [comment]
mmh I am unsure either. Afaik, `binfmt-support` is the module which allow interpreter to register.

`qemu-user-static` are the interpreter statically compiled.

`qemu` might actually register.
